### ISSUE TITLE
Tokeniser Disco

### ISSUE THREAD

**Issue by christoph-hart** [jzrake/MclTextEditor#1]
The code tokeniser seems to only parse the visible text, which creates weird results when the first line is in the middle of a multi-line comment:

![tokeniser_disco](https://user-images.githubusercontent.com/6277426/42045990-254190c4-7afd-11e8-8b59-b2b2e69c5d3a.gif)

**Comment by jzrake** [comment]
Thanks, I'm aware of that. There are many solutions. Choice paralysis!

**Comment by jzrake** [comment]
This is fixed, for now. I added an option to navigate indexes by token value, and I just start the tokenizer from the token before the first one on screen. Also note there's a debug mode to render token values in place of the text characters. For now you can access it via the popup.
