### ISSUE TITLE
Convert to JUCE module?

### ISSUE THREAD

**Issue by christoph-hart** [jzrake/MclTextEditor#2]
I think it would be better to make this a dedicated JUCE module and split the big TextEditor.cpp / .h files into one per class. Compilation time will not change because it will be merged into one big .h / .cpp file in the module.

If you don't have the time to do this or don't know how to use the JUCE module format, I'll happily make a pull request (it will be a matter of minutes).

**Comment by jzrake** [comment]
Sure, I'd be interested to see how to use the module format, if you've got the time!

**Comment by christoph-hart** [comment]
There you go:

https://github.com/jzrake/MclTextEditor/pull/4
